export const jobData = [
  {
    id: "recAGlfik4CeaV0HL",
    order: 7,
    title: "Software Application Developer",
    dates: "Feb 2020 - June 2021",
    duties: [
      "Developing an internal application using Angular JS 1.6 and React on the front end, Node, Hapi and PHP for API, GOLANG for services for Regional Operating Centre Specialists, Supervisors, Maintenance Technicians",
      "Developing map services using Google Map API for displaying various entities like Accounts, Nodes, etc",
      "Working with a third party company API that keeps track of the truck location of the maintenance technicians and displaying them in the maps used in the Application.",
      "Porting legacy code base to our custom library using ES6, which is used across other applications of the company.",
      "Other technologies/frameworks/libraries currently using are UnderscoreJS and D3JS",
      "Writing unit test cases using Karma and Cypress for E2E testing for the application.",
      "Used BitBucket for the version control and JIRA for ticket tracking systems",
      "Involved in User Experience and Validation during designing and comp sign offs.",
      "Creating wireframes and mocks using Adobe Photoshop, InDesign and XD.",
      "Creating SVG assets using Adobe Photoshop for the frontend design and development.",
      "Involved in complete software life cycle and deploying of the project in the multiple environments.",
      "Following Agile-Scrum for software development.",
    ],
    company: "Charter Communications",
  },
  {
    id: "recnGJfik4CeaV0HL",
    order: 6,
    title: "Software Application Developer",
    dates: "Oct 2019 - Feb 2020",
    duties: [
      "Developing an internal application using React on the front end, Node, Express, Node-Red for API and Micro-services and Oracle SQL and Mongo Database.",
      "Developing microservices using NodeJS and ExpressJS that are connected to the Oracle Databases",
      "Working with Node-red, a programming tool for wiring APIs and online services, for developing additional micro services that consume MongoDB documents.",
      "Porting legacy code base to our custom library using ES6, which is used across other applications of the company.",
      "Working on MongoDB and building out schemas and documents for the API microservices.",
      "Developing new schemas, tables, relational databses in Oracle SQL Database.",
      "Other technologies/frameworks/libraries currently using are UnderscoreJS and D3JS",
      "Writing unit test cases using Karma and Jasmine for testing for the application.",
      "Using GITLAB for the version control and RALLY for ticket tracking systems",
      "Involved in User Experience and Validation during designing and comp sign offs.",
      "Creating wireframes and mocks using Adobe Photoshop, InDesign and XD.",
      "Creating SVG assets using Adobe Photoshop for the frontend design and development.",
      "Involved in complete software life cycle and deploying of the project in the multiple environments.",
      "Following Agile-Scrum for software development.",
    ],
    company: "Florida Blue",
  },
  {
    id: "recAGJfik4CeaV0HL",
    order: 5,
    title: "Software Application Developer",
    dates: "Mar 2017 - Oct 2019",
    duties: [
      "Developing an internal application using Angular JS 1.6 and React on the front end, Node, Hapi and PHP for API, GOLANG for services for Regional Operating Centre Specialists, Supervisors, Maintenance Technicians",
      "Developing map services using Google Map API for displaying various entities like Accounts, Nodes, etc",
      "Working with a third party company API that keeps track of the truck location of the maintenance technicians and displaying them in the maps used in the Application.",
      "Porting legacy code base to our custom library using ES6, which is used across other applications of the company.",
      "Other technologies/frameworks/libraries currently using are UnderscoreJS and D3JS",
      "Writing unit test cases using Karma and Cypress for E2E testing for the application.",
      "Used BitBucket for the version control and JIRA for ticket tracking systems",
      "Involved in User Experience and Validation during designing and comp sign offs.",
      "Creating wireframes and mocks using Adobe Photoshop, InDesign and XD.",
      "Creating SVG assets using Adobe Photoshop for the frontend design and development.",
      "Involved in complete software life cycle and deploying of the project in the multiple environments.",
      "Following Agile-Scrum for software development.",
    ],
    company: "Charter Communications",
  },
  {
    id: "recAGJfiU4CeaV0HL",
    order: 4,
    title: "Javascript Web Developer",
    dates: "Nov 2016 - Mar 2017",
    duties: [
      "Developed an internal application using ReactJS and NodeJS for Relationship Mangers",
      "Involved in writing NodeJS server using HapiJS framework and plugins",
      "Developed NodeJS REST API’s and web services",
      "Developied custom authentication using schema strategies of HapiJS",
      "Worked on Redis for storing and retrieving user preferences",
      "Gained experience in MongoDB by working on storing user states",
      "Developed validations using Joi plugins",
      "Developed test cases using Mocha-Chai for the routes, APIs and controllers used in the Node/Hapi server",
      "Involved in developing Data Domain models and sample data for creating API",
      "Managing API design life cycle using API Blueprint and Swagger for developing prototypes and model APIs that describe already deployed critical APIs",
      "Used GITHUB for the version control",
      "Involved in User Experience and Validation during designing and comp sign offs",
      "Created wireframes and mocks using Adobe Photoshop and InvisionApp",
      "Created SVG assets for the frontend design and development",
      "Involved in complete software life cycle and deploying of the project in the environments",
      "Experience on Cloud Platform As A Service (PaaS)",
      "Followed Agile-Scrum for software development",
    ],
    company: "American Express",
  },
  {
    id: "recIL6mJNfWObonls",
    order: 3,
    title: "Front-End Developer",
    dates: "Mar 2016 - September 2016",
    duties: [
      "Developed Customer facing applications using ExtJS for Company’s Carriers, Shippers and Drivers",
      "Involved in writing custom ExtJS components and utilities",
      "Developed the landing pages with Sencha ExtJS 6.x.x, Ext templates, HTML5, Javascipt, SCSS",
      "Worked on Modern Version of the application screens to be responsive in mobiles and tablets",
      "Developed reusable Ext XTemplates for various purposes in the project",
      "Used ExtJS charting features to provide great visual and detailed reports for the users",
      "Implemented client-side validations using ExtJS and AJAX Library",
      "Developed web pages compliant to W3C and ADA as well as Company standards",
      "Worked on variety of tasks which included building reusable Ext components",
      "Worked on developing stores for Ajax calls to consume REST API’s",
      "Worked extensively on Ext packages that were available locally and remotely for other projects",
      "Reused ESRI map components in the application to determine origin and destination of loads",
      "Used UXPin for creating/udating mock ups for the application",
      "Performed unit tests to the codebase using Jasmine",
      "Involved in complete SDLC - Requirement Analysis, Development, System and Integration Testing",
      "Used Polarion for requirements, tasks and defects tracking, Trello for task tracking and time management and Codebrag for code reviews",
      "Followed Agile-Scrum for software development",
    ],
    company: "j.b. hunt transport inc",
  },
  {
    id: "rec61x18GVY99hQq5",
    order: 2,
    title: "Junior Software Developer",
    dates: "May 2014 - September 2015",
    duties: [
      "Involved in developing the UI pages using HTML, CSS, Bootstrap, JavaScript, AngularJS, JSON, jQuery, Ajax for multiple clients of the company",
      "Used jQuery core library functions for the logical implementation part at client side for all the applications",
      "Used AngularJS to create dynamic components for the web applications",
      "Used D3JS to create reporting charts for analytics",
      "Created interactive Axure and UXPin prototypes of the company’s in-house digital marketing software for implementing new features and functionalities",
      "Analyzed, designed and developed a new system with D3 Charts reporting to replace an existing one to help Sales team get intuitive reports",
      "Designed images, logos, banners, sitemaps and animations for presentation and web development purposes using Adobe Photoshop, Fireworks, Flash and Illustrator",
      "Researched and implemented best practices and user trends",
      "Debug the application using Firebug to traverse the documents and manipulated the Nodes using DOM and DOM Functions using Firefox and IE Developer Tool bar for IE",
    ],
    company: "technumen inc",
  },
  {
    id: "rec61x18GVY33hQq5",
    order: 1,
    title: "graduate research assistant - web developer",
    dates: "august 2013 - dec 2014",
    duties: [
      "Involved in Department website maintenance in WordPress Content Management System, HTML, CSS, JavaScript",
      "Developing Web pages for various informational needs for the Department of College of Technology (CoT) in WordPress with HTML, CSS and JavaScript",
      "Produced design sketches, recommended interaction behaviors, developed prototypes and created designs for review and approval to ensure that user requirements were met",
      "Maintaining alumni and current grad student records on internal MS Access data base",
      "Updating news-letter and graduate aide lists in all COT department webpages of Grad School",
      "Worked with Photoshop, InDesign for enhancing quality of the images in COT department website",
      "Creating posters, banners and brochures for information and orientation needs of College of Technology with Adobe Photoshop, Illustrator and InDesign",
      "Updating information regarding Teaching/Research assistants in CoT website and university notice boards",
      "Critiqued and suggested enhancements towards improving user interfaces in existing Web applications",
      "Assisting Professors with graduate level courses by maintaining the course materials on University course portal, BlackBoard",
      "Grading assignments and tests of the Grad Students",
      "Attending to any issues related to Course materials, technical difficulties with the software used for course purposes, questions and doubts regarding day-to-day classes, assignments and tests",
      "Designed images, logos, banners, sitemaps and animations for presentation purposes using Adobe Fireworks, Flash and Illustrator",
    ],
    company: "purdue university calumet",
  },
];
